### ISSUE TITLE
errore par 18.4

### ISSUE THREAD

**Issue by GiuliaSalzano** [dodogabrie/Sistemi-Complessi#3]
Quando calcoliamo la traslazione temporale t2 per \theta1 (quindi nella formula \theta1(t + t2)) nella prima uguaglianza va messo w1t2 non w1t1

**Comment by dodogabrie** [comment]
Se lo faccio la formula non torna più nemmeno ai passaggi successivi... Sicura?

**Comment by dodogabrie** [comment]
> Quando calcoliamo la traslazione temporale t2 per \theta1 (quindi nella formula \theta1(t + t2)) nella prima uguaglianza va messo w1t2 non w1t1

Se lo faccio la formula non torna più nemmeno ai passaggi successivi... Sicura?

**Comment by GiuliaSalzano** [comment]
sisi torna con i passaggi dopo, guarda la formula sopra per t2

**Comment by dodogabrie** [comment]
> sisi torna con i passaggi dopo, guarda la formula sopra per t2

Corretto! mi stavo confondendo tra w2 e t2 nel messaggio :(
